# Generated by Django 5.0.6 on 2024-06-22 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stickynote',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
