# Generated by Django 5.0.6 on 2024-06-23 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stickynote',
            name='is_visible',
            field=models.BooleanField(default=True),
        ),
    ]
